# Generated by Django 5.1.15 on 2026-10-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothroll',
            name='cool_down_full',
            field=models.BooleanField(default=False, verbose_name='冷却已满'),
        ),
    ]
